import { resolveTxt } from "node:dns/promises";
import { authoritiesFor, loadOurLexicons } from "./lexicon-files.mjs";

const args = process.argv.slice(2);
const wanted = args.find((arg) => !arg.startsWith("-"));
const expectedDid = wanted ?? process.env.LEXICON_DID ?? null;
const zoneOnly = args.includes("--zone");
const zoneTtl = 3600;

const lookup = async (authority) => {
	try {
		const records = await resolveTxt(`_lexicon.${authority}`);
		for (const chunks of records) {
			const value = chunks.join("");
			if (value.startsWith("did=")) return value.slice(4).trim();
		}
		return null;
	} catch (cause) {
		if (cause.code === "ENOTFOUND" || cause.code === "ENODATA") return null;
		return { error: cause.code ?? String(cause) };
	}
};

const docs = await loadOurLexicons();
const authorities = authoritiesFor(docs);

const zone = () => {
	const did = expectedDid ?? "did:plc:YOURDID";
	const apex = "colibri.social";
	const rows = [...authorities].map(([authority, nsids]) => {
		const name = `_lexicon.${authority}`;
		const relative = name.endsWith(`.${apex}`) ? name.slice(0, -(apex.length + 1)) : name;
		return { relative, nsids };
	});
	const width = Math.max(...rows.map((row) => row.relative.length));

	const lines = [
		"; Lexicon NSID authority records for the social.colibri.beta.* namespace.",
		";",
		"; One record per NSID domain authority, which is every NSID segment but the",
		"; last, reversed. social.colibri.beta.channel.text therefore resolves through",
		"; _lexicon.channel.beta.colibri.social.",
		";",
		`; Generated by 'pnpm lexicons:check-dns --zone' from ${docs.length} lexicons.`,
		"; Regenerate rather than editing by hand.",
		";",
		"; This is a record fragment, not a loadable standalone zone: it carries no SOA",
		"; or NS so that importing it cannot disturb the rest of the zone. Cloudflare's",
		"; DNS import accepts it as is and adds these records alongside the existing",
		"; ones. To use it with BIND directly, $INCLUDE it from a zone that has an SOA.",
		"",
		`$ORIGIN ${apex}.`,
		`$TTL ${zoneTtl}`,
		"",
	];
	for (const row of rows) {
		lines.push(
			`${row.relative.padEnd(width)}  IN  TXT  "did=${did}"   ; ${row.nsids.length} lexicon${row.nsids.length === 1 ? "" : "s"}`,
		);
	}
	lines.push("");
	return lines.join("\n");
};

if (zoneOnly) {
	process.stdout.write(zone());
	process.exit(0);
}

console.log(`${docs.length} lexicons across ${authorities.size} NSID authorities`);
console.log("a wildcard TXT record on the zone does not count: only a did= value resolves\n");

const missing = [];
const mismatched = [];
let resolved = 0;

for (const [authority, nsids] of authorities) {
	const found = await lookup(authority);
	const label = `_lexicon.${authority}`;
	if (found === null) {
		missing.push(authority);
		console.log(`  missing   ${label}  (${nsids.length} lexicons)`);
	} else if (typeof found === "object") {
		missing.push(authority);
		console.log(`  ERROR     ${label}  ${found.error}`);
	} else if (expectedDid && found !== expectedDid) {
		mismatched.push({ authority, found });
		console.log(`  MISMATCH  ${label}  -> ${found}`);
	} else {
		resolved += 1;
		console.log(`  ok        ${label}  -> ${found}`);
	}
}

if (missing.length > 0) {
	const example = expectedDid ?? "did:plc:YOURDID";
	console.log("\nAdd these DNS TXT records:\n");
	for (const authority of missing) {
		console.log(`    _lexicon.${authority}\tTXT\t"did=${example}"`);
	}
	console.log("\nMost DNS interfaces want only the subdomain part, so drop the trailing");
	console.log("registered domain when entering the name.");
}

if (mismatched.length > 0) {
	console.log(`\n${mismatched.length} authorities resolve to a different DID than ${expectedDid}.`);
	console.log("Publishing under those NSIDs will be refused.");
}

console.log(`\n${resolved} resolved, ${missing.length} missing, ${mismatched.length} mismatched`);
process.exit(missing.length + mismatched.length > 0 ? 1 : 0);
